import {
    GetFaqDataReducer, addFAQreducer, deleteFaqReducer, getIdToEditReducer, updateFAQreducer, inputReducer, getallcustomer, loginstatus,
    getallpackages, getIdToEditPackageReducer, GetCDatareducer, ChatFilereducer, updatePackagereducer, addPackagereducer,
    StatusChangecustomer, addCustomersreducer, GetactiveFaqDataReducer, addondata, GetPackageDataReducer, packagedata, booksdataimage,
    Addaddondata, Addaddondatabyid, PackageAddonDataReducer, booksinnerreducer, booksIddataimage, frontendloginreducer, cartreducer,
    lengthcartreducer, orderplacereducer, allorderreducer, adminallorderreducer, adminallorderbyidreducer, 
    zoomtoken, zoommeetingurl,zoomMeetinReq,zoomMeeting,
    paypalorderreducer, paypalthanyouidreducer, recaptchareducer, Adminchatreducer, Adminchatuserreducer, GetAdminMsgReducer,
    Adminchatlinkimagereducer, ChatLinksReducer, GetFrontChatNumReducer, AddReviewsReducer, GetProductsReviewsReducer,
    GetProductsReviewsSumReducer, GetFiveStarProductsReviewsReducer, GetFourStarProductsReviewsReducer, GetThreeStarProductsReviewsReducer,
    GetTwoStarProductsReviewsReducer, GetOneStarProductsReviewsReducer, Getmsgforsavebook, Getmsgforpackageupdate, CartItemsLengthReducer, 
    Getmsgforaddonupdate, SaveBooksReducer, GetmsgforIntakeForm, GetmsgforWriteResume, GetmsgforuserIntakeForm, GetUserIntakeFormData,
    AllManageOrderReducer, GetUserIntakeFormById, GetUserIntakeFormUpdated, AdminQuestionnaireReducer, AdminQuestionnaireIdReducer
} from './Reducer'

import { togglingReducer } from './Reducer'
import { combineReducers } from "redux";

const rootReducer = combineReducers({
    getIdToEditReducer,
    deleteFaqReducer,
    addFAQreducer,
    updateFAQreducer,
    GetFaqDataReducer,
    togglingReducer,
    inputReducer,
    getallcustomer,
    loginstatus,
    getallpackages,
    getIdToEditPackageReducer,
    updatePackagereducer,
    addPackagereducer,
    StatusChangecustomer,
    addCustomersreducer,
    GetactiveFaqDataReducer,
    addondata,
    GetPackageDataReducer,
    packagedata,
    booksdataimage,
    Addaddondata,
    Addaddondatabyid,
    PackageAddonDataReducer,
    booksinnerreducer,
    booksIddataimage,
    frontendloginreducer,
    cartreducer,
    lengthcartreducer,
    orderplacereducer,
    allorderreducer,
    adminallorderreducer,
    adminallorderbyidreducer,
    zoomtoken,
    zoommeetingurl,
    zoomMeetinReq,
    zoomMeeting,
    paypalorderreducer,
    paypalthanyouidreducer,
    recaptchareducer,
    Adminchatreducer,
    Adminchatuserreducer,
    GetAdminMsgReducer,
    Adminchatlinkimagereducer,
    ChatFilereducer,
    ChatLinksReducer,
    GetCDatareducer,
    GetFrontChatNumReducer,
    AddReviewsReducer,
    GetProductsReviewsReducer,
    GetProductsReviewsSumReducer,
    GetFiveStarProductsReviewsReducer,
    GetFourStarProductsReviewsReducer,
    GetThreeStarProductsReviewsReducer,
    GetTwoStarProductsReviewsReducer,
    GetOneStarProductsReviewsReducer,
    Getmsgforsavebook,
    CartItemsLengthReducer,
    Getmsgforpackageupdate,
    Getmsgforaddonupdate,
    SaveBooksReducer,
    GetmsgforIntakeForm,
    GetmsgforWriteResume,
    GetmsgforuserIntakeForm,
    GetUserIntakeFormData,
    AllManageOrderReducer,
    GetUserIntakeFormById,
    GetUserIntakeFormUpdated,
    AdminQuestionnaireReducer,
    AdminQuestionnaireIdReducer

})
export default rootReducer;